### PR TITLE
update to net6

### PR DESCRIPTION
**Pull request by lxymahatma**
add setting file for whether to show mean delay in victory screen or not

### CODE REVIEW

**Comment by Azn9** [comment]
Wow
So there are people that use this mod 😂

Seeing the amount of work and changes, feel free to add yourself to the author list!

**Comment by lxymahatma** [comment]
> Wow So there are people that use this mod 😂
> 
> Seeing the amount of work and changes, feel free to add yourself to the author list!

yeah many people (like 5 or more) ask me to update this to .net6 so i just update it and pr it 👍
~~tbh they didnt even ask me to update my mods lol~~
i'll add myself to author list very soon ~~actually it's just some small work not that amount tho~~

**Comment by lxymahatma** [comment]
hm someone send me this picture, guess I'll try to figure it out tomorrow and then u can merge this pr

**Comment by lxymahatma** [comment]
done, should work fine now ig

**Review by Azn9 — APPROVED** [review]

**Pull request merged**
